version: '3'

services:
  backend:
    image: backend
    ports: 
      - 8000:8000
    environment: 
      - FRONT_URL=http://localhost
      - REDIS=redis
      - DB_USERNAME=tester
      - DB_PASSWORD=example
      - DB_HOST=db
    
  frontend:
    image: frontend
    ports: 
      - 5000:5000
    environment: 
      - API_URL=http://localhost/api

  redis:
    image: redis

  db:
    image: postgres
    environment: 
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=example

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      