version: '3'

services:
  backend:
    image: ml-kurkkumopo-backend
    build: ./ml-kurkkumopo-backend
    ports: 
      - 5000:5000
    volumes:
      - /model:/src/model
    
  frontend:
    image: ml-kurkkumopo-frontend
    build: ./ml-kurkkumopo-frontend
    ports: 
      - 3000:3000

  training:
    image: ml-kurkkumopo-training
    build: ./ml-kurkkumopo-training
    volumes:
      - /model:/src/model
      - /imgs:/src/imgs